//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.24 at 10:41:57 PM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "uri:iso.org:21090", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package edu.emory.cci.aim.model;
